apiVersion: v1
kind: Service
metadata:
  name: myms 
  labels:
    app: myms 
spec:
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  selector:
    app: myms

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: myms 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myms 
    spec:
      containers:
      - name: myms
        image: jazzdd/alpine-flask:python3
        command: ["sh"]
        args: ["-c", "printf \"import flask\\nimport uuid\\nimport hashlib\\napp = flask.Flask(__name__)\\n@app.route(\\\"/\\\")\\ndef hello():\\n    for i in range(0,800000):\\n     hashlib.sha224(uuid.uuid4().hex.upper()[0:6].encode()).hexdigest()\\n    return \\\"Done\\\"\\napp.run(host=\\\"0.0.0.0\\\", threaded=True)\" > script.py && python3 script.py"]
        ports:
        - name: http-port
          containerPort: 5000
        resources:
          requests:
            cpu: 200m

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  namespace: default
  name: myms
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: myms
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
